import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
// import {} from ''
import "./globals.css";
import Providers from "@/components/Providers";
import { NavBar } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <NavBar />
        <main>

          <Providers>
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
