
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET
const DJANGO_CLIENT_ID = process.env.DJANGO_CLIENT_ID

export {
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    DJANGO_CLIENT_ID,
}